# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
variables:
  # Get the current date in YYYYMMDD format using PowerShell
  currentDate: $[format('{0:yyyyMMdd}', pipeline.startTime)]

name: '$(Build.DefinitionName)_$(Build.BuildId)_$(variables.currentDate)_$(Build.SourceBranchName)'

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(system.defaultworkingdirectory)/webapp/target/webapp.war'
    ArtifactName: 'drop'
    publishLocation: 'Container'
# - task: InvokeRESTAPI@1
#   inputs:
#     connectionType: 'connectedServiceNameARM'
#     azureServiceConnection: 'Pay-As-You-Go (4fb0e611-792d-4836-abce-dcc34575e5c3)'
#     method: 'POST'
#     waitForCompletion: 'false'

