# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
variables:
  # Get the current date in YYYYMMDD format
  currentDate: $[format('{0:yyyyMMdd}', pipeline.startTime)]

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- powershell: 
   $pipelineName = "$(Build.DefinitionName)_$(Build.BuildId)_$(variables.currentDate)_$(Build.SourceBranchName)"
        Write-Host "##vso[task.setvariable variable=pipelineName]$pipelineName"


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(system.defaultworkingdirectory)/webapp/target/webapp.war'
    ArtifactName: 'drop'
    publishLocation: 'Container'


